Added sample TA and TP information to the printouts from HDF5LIBS_TestDumpRecord
DUNE-DAQ/hdf5libs pull request #78
Opened 2024-04-01 14:58 UTC by bieryAtFnal

Also added information printed out about TP/TA/TC fragment sizes.

I expect that these additions will be useful when verifying that the correct TAs and TPs are included in fragments within the TriggerRecord.

2024-04-01 15:05 UTC, bieryAtFnal commented
Here are sample instructions for demonstrating these changes:

```
source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
setup_dbt latest
dbt-create -b candidate fddaq-v4.4.0-rc3-a9 01AprFDv4.4.0rc3
cd 01AprFDv4.4.0rc3/sourcecode
git clone https://github.com/DUNE-DAQ/daqsystemtest.git -b v2.3.0
git clone https://github.com/DUNE-DAQ/hdf5libs.git -b kbiery/sample_tatp_printout_TestDumpRecord
cd ..

dbt-workarea-env
dbt-build -j 20
dbt-workarea-env

mkdir rundir
cd rundir

cat <<EOF1 > daqconf.json
{
  "boot": {
    "use_connectivity_service": true,
    "start_connectivity_service": true,
    "connectivity_service_host": "localhost",
    "connectivity_service_port": 15432
  }, 
  "daq_common": {
    "data_rate_slowdown_factor": 1
  },
  "detector": {
    "clock_speed_hz": 62500000
  },
  "readout": {
    "use_fake_cards": true,
    "default_data_file": "asset://?checksum=dd156b4895f1b06a06b6ff38e37bd798",
    "generate_periodic_adc_pattern": true,
    "emulated_TP_rate_per_ch": 1,
    "enable_tpg": true,
    "tpg_threshold": 500,
    "tpg_algorithm": "SimpleThreshold"
  },
  "trigger": {
    "ttcm_input_map": [{"signal": 1, "tc_type_name": "kTiming",
                        "time_before": 1000, "time_after": 1000}],
    "trigger_activity_plugin": ["TriggerActivityMakerPrescalePlugin"],
    "trigger_activity_config": [ {"prescale": 25} ],
    "trigger_candidate_plugin": ["TriggerCandidateMakerPrescalePlugin"],
    "trigger_candidate_config": [ {"prescale": 100} ],
    "mlt_merge_overlapping_tcs": false
  },
  "dataflow": {
    "apps": [ { "app_name": "dataflow0" } ],
    "enable_tpset_writing": true,
    "token_count": 20
  },
  "hsi": {
    "random_trigger_rate_hz": 1.0
  }
}
EOF1

cat <<EOF2 > dro_map.json
[
    {
        "src_id": 100,
        "geo_id": {
            "det_id": 3,
            "crate_id": 1,
            "slot_id": 0,
            "stream_id": 0
        },
        "kind": "eth",
        "parameters": {
            "protocol": "udp",
            "mode": "fix_rate",
            "rx_iface": 0,
            "rx_host": "localhost",
            "rx_pcie_dev": "0000:00:00.0",
            "rx_mac": "00:00:00:00:00:00",
            "rx_ip": "0.0.0.0",
            "tx_host": "localhost",
            "tx_mac": "00:00:00:00:00:00",
            "tx_ip": "0.0.0.0"
        }
    },
    {
        "src_id": 101,
        "geo_id": {
            "det_id": 3,
            "crate_id": 1,
            "slot_id": 0,
            "stream_id": 1
        },
        "kind": "eth",
        "parameters": {
            "protocol": "udp",
            "mode": "fix_rate",
            "rx_iface": 0,
            "rx_host": "localhost",
            "rx_pcie_dev": "0000:00:00.0",
            "rx_mac": "00:00:00:00:00:00",
            "rx_ip": "0.0.0.0",
            "tx_host": "localhost",
            "tx_mac": "00:00:00:00:00:00",
            "tx_ip": "0.0.0.0"
        }
    },
    {
        "src_id": 102,
        "geo_id": {
            "det_id": 3,
            "crate_id": 2,
            "slot_id": 0,
            "stream_id": 0
        },
        "kind": "eth",
        "parameters": {
            "protocol": "udp",
            "mode": "fix_rate",
            "rx_iface": 1,
            "rx_host": "localhost",
            "rx_pcie_dev": "0000:00:00.1",
            "rx_mac": "00:00:00:00:00:01",
            "rx_ip": "0.0.0.1",
            "tx_host": "localhost",
            "tx_mac": "00:00:00:00:00:00",
            "tx_ip": "0.0.0.0"
        }
    },
    {
        "src_id": 103,
        "geo_id": {
            "det_id": 3,
            "crate_id": 2,
            "slot_id": 0,
            "stream_id": 1
        },
        "kind": "eth",
        "parameters": {
            "protocol": "udp",
            "mode": "fix_rate",
            "rx_iface": 1,
            "rx_host": "localhost",
            "rx_pcie_dev": "0000:00:00.1",
            "rx_mac": "00:00:00:00:00:01",
            "rx_ip": "0.0.0.1",
            "tx_host": "localhost",
            "tx_mac": "00:00:00:00:00:00",
            "tx_ip": "0.0.0.0"
        }
    },
    {
        "src_id": 104,
        "geo_id": {
            "det_id": 3,
            "crate_id": 3,
            "slot_id": 0,
            "stream_id": 0
        },
        "kind": "eth",
        "parameters": {
            "protocol": "udp",
            "mode": "fix_rate",
            "rx_iface": 2,
            "rx_host": "localhost",
            "rx_pcie_dev": "0000:00:00.2",
            "rx_mac": "00:00:00:00:00:02",
            "rx_ip": "0.0.0.2",
            "tx_host": "localhost",
            "tx_mac": "00:00:00:00:00:00",
            "tx_ip": "0.0.0.0"
        }
    },
    {
        "src_id": 105,
        "geo_id": {
            "det_id": 3,
            "crate_id": 3,
            "slot_id": 0,
            "stream_id": 1
        },
        "kind": "eth",
        "parameters": {
            "protocol": "udp",
            "mode": "fix_rate",
            "rx_iface": 2,
            "rx_host": "localhost",
            "rx_pcie_dev": "0000:00:00.2",
            "rx_mac": "00:00:00:00:00:02",
            "rx_ip": "0.0.0.2",
            "tx_host": "localhost",
            "tx_mac": "00:00:00:00:00:00",
            "tx_ip": "0.0.0.0"
        }
    }
]
EOF2

fddaqconf_gen -c ./daqconf.json --detector-readout-map-file ./dro_map.json mdapp_wibeth_tpg

nanorc --partition-number 2 mdapp_wibeth_tpg ${USER}-test boot conf start_run 101 wait 20 stop_run scrap terminate

HDF5LIBS_TestDumpRecord swtest*run000101*.hdf5
```

2024-04-02 07:17 UTC, aeoranday requested changes
I tested with your example and an older HDF5. I found that it works in both cases. However, there are some corrections needed for the printouts.

I think that including "First TX..." for each case is sufficient since `trgtools` goes into more depth for each of the TXs in a fragment, and it may become unwieldy to print for larger TAs/TCs.

2024-04-02 07:17 UTC, aeoranday commented on test/apps/HDF5LIBS_TestDumpRecord.cpp
> +        ss << "\n\t\t" << "First TP type = " << static_cast<int>(tpptr->type) << ", TA algorithm = "
This should have `TP algorithm` not `TA`.

2024-04-02 07:17 UTC, aeoranday commented on test/apps/HDF5LIBS_TestDumpRecord.cpp
> +               (taptr->n_inputs * sizeof(TriggerPrimitive))) << ")";
This only looks at the first TA in the fragment, so this should be a similar language to the TP case. I'm also realizing that this change is needed for the TC case as well.

2024-04-03 15:24 UTC, aeoranday approved these changes
LGTM.

2024-04-03 18:00 UTC, merged