Added a check on the TRH version in HDF5LIBS_TestDumpRecord
DUNE-DAQ/hdf5libs pull request #80
Opened 2024-04-07 19:52 UTC by bieryAtFnal

This will be helpful in avoiding confusion if users happen to run the new version of the utlitiy on older data files.

To test these changes, run the HDF5LIBS_TestDumpRecord application on raw data files produced with fddaq-v4.3.0 or earlier and confirm that an error message is printed out.

2024-04-08 05:05 UTC, aeoranday requested changes
There is a language mistake in the expected vs found version printout. I thought I was compiling incorrectly for a moment!

2024-04-08 05:05 UTC, aeoranday commented on test/apps/HDF5LIBS_TestDumpRecord.cpp
> +                  << TriggerRecordHeaderData::s_trigger_record_header_version << ".)" << std::endl;
This language is flipped: "Expected" should be the one attached to `TriggerRecordHeaderData` and "found" should be from the `get_header()`.

2024-04-08 16:38 UTC, bieryAtFnal commented
wow, sorry, thanks for catching that.
Fixed now.

2024-04-09 04:49 UTC, aeoranday approved these changes
LGTM.

2024-04-09 12:20 UTC, merged